server:
  ip_address: "0.0.0.0"
  port: "8099"
  saved_data_path: "result"
parameter:
  embeddings_name: "sentence-transformers/all-MiniLM-L6-v2"

  DATA_PATH: "data/"
  DB_FAISS_PATH: "vectorstore/db_faiss"
  DB_MESSAGES: "db_messages/"

  # Số đoạn sẽ được thêm vào lời nhắc. Quá nhiều đoạn trích và bạn có nguy cơ bị cả lời nhắc vượt qua
  # giới hạn mã thông báo và mô hình không thể tìm thấy câu trả lời chính xác
  prompt_number_snippets: 5

  # GPT related constants
  gpt_model_to_use: "gpt-3.5-turbo-16k"

  temperature: 0
  gpt_max_tokens: 256

  # Số tin nhắn của người dùng trước đây sẽ được sử dụng để tìm kiếm các đoạn có liên quan
  search_number_messages: 3

  # PDF Chunking constants
  chunk_size: 128
  chunk_overlap: 24

  # Số đoạn trích được FAISS truy xuất
  number_snippets_to_retrieve: 5
  
  #Thông tin sản phẩm
  data_private: ./data/product_final_204_oke.xlsx

  num_product: 3  # Số lượng sản phẩm tối đa cần tìm
  #
  raw_answer: ["Mình là trợ lý AI của VCC. Mình được tạo ra để hỗ trợ và giải đáp về các sản phẩm của VCC, hiện tại mình vẫn đang trong quá trình phát triển nên không phải lúc nào cũng đúng. Bạn có thể phản hồi để giúp mình cải thiện tốt hơn.",
                "Mình là trợ lý AI của VCC. Mình được tạo ra để hỗ trợ và giải đáp về các sản phẩm của VCC như: Thông tin sản phẩm, giá tiền, số lượng, thông số sản phẩm, . . . Hãy hỏi mĩnh những thông tin này để mình giúp đỡ."]


yolo_params:
  weight_path: "weight/weight_26_100ep.pt"
  conf_thres: 0.3
  classes: {
            0: 'Bàn chải điện',
            1: 'Bàn là',
            2: 'Bếp từ',
            3: 'Bình đun nước',
            4: 'Bình nóng lạnh',
            5: 'Đèn năng lượng mặt trời',
            6: 'Điều hòa',
            7: 'Ghế massage Daikiosan',
            8: 'Lò vi sóng',
            9: 'Máy cạo râu',
            10: 'Máy đánh trứng',
            11: 'Máy ép',
            12: 'Máy giặt',
            13: 'Máy hút bụi',
            14: 'Máy lọc không khí',
            15: 'Máy lọc nước',
            16: 'Máy sấy tóc',
            17: 'Máy xay',
            18: 'Nồi áp suất',
            19: 'Nồi chiên không dầu',
            20: 'Nồi cơm điện',
            21: 'Robot hút bụi',
            22: 'Thiết bị Webcam',
            23: 'Thiết bị Wifi',
            24: 'Thiết bị camera',
            25: 'Lò nướng'
        }